---
author:
  - 'Thomas Sibley <trs@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-OpenID-Consumer
no_index:
  directory:
    - inc
    - t
requires:
  Cache::FileCache: 0
  HTTP::Server::Simple: 0
  LWP::UserAgent::Paranoid: 0
  Net::OpenID::Consumer: 0
  Test::Builder: 0
  Test::HTTP::Server::Simple: 0
resources:
  license: http://dev.perl.org/licenses/
version: '0.02'
